name: Test var2file Script
on:
  push:
    paths:
      - "var2file.py"
      - .github/workflows/test_var2file.yml
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  TASK_CONTENTS: ${{ vars.TASK_DEFINITION_CONTENT_SAMPLE }}

jobs:
  save-file:
    runs-on: [self-hosted, X64, Linux]
    name: Save File
    steps:
      - uses: actions/checkout@v4
      - run: echo $TASK_CONTENTS
      - run: python var2file.py TASK_CONTENTS task.yml
      - run: cat task.yml
